// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9CQrli2VORjO8AjqoP9jsTJ3eKC_CFuo',
    appId: '1:257427015937:web:25af3d36f36f1d12b57300',
    messagingSenderId: '257427015937',
    projectId: 'revenueflow-c6f8a',
    authDomain: 'revenueflow-c6f8a.firebaseapp.com',
    storageBucket: 'revenueflow-c6f8a.appspot.com',
    measurementId: 'G-LTYFPJ98LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAakIzgedYO7wZ0iCZEtkfwyhQNXQt-bOE',
    appId: '1:257427015937:android:34c3874971c5fba7b57300',
    messagingSenderId: '257427015937',
    projectId: 'revenueflow-c6f8a',
    storageBucket: 'revenueflow-c6f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcrJBRyTjUB_mCHod6QbKPUsxZwy_I7Ic',
    appId: '1:257427015937:ios:36df84369afcb85fb57300',
    messagingSenderId: '257427015937',
    projectId: 'revenueflow-c6f8a',
    storageBucket: 'revenueflow-c6f8a.appspot.com',
    iosBundleId: 'uz.evolution.revenueFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcrJBRyTjUB_mCHod6QbKPUsxZwy_I7Ic',
    appId: '1:257427015937:ios:36df84369afcb85fb57300',
    messagingSenderId: '257427015937',
    projectId: 'revenueflow-c6f8a',
    storageBucket: 'revenueflow-c6f8a.appspot.com',
    iosBundleId: 'uz.evolution.revenueFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9CQrli2VORjO8AjqoP9jsTJ3eKC_CFuo',
    appId: '1:257427015937:web:656fdd217122d992b57300',
    messagingSenderId: '257427015937',
    projectId: 'revenueflow-c6f8a',
    authDomain: 'revenueflow-c6f8a.firebaseapp.com',
    storageBucket: 'revenueflow-c6f8a.appspot.com',
    measurementId: 'G-HLQS52ME0N',
  );
}
